Admin should be able to assign driver from dropdown
ucsb-cs156-s24/proj-gauchoride-s24-5pm-5 pull request #23
Opened 2024-05-17 07:42 UTC by Ononymous

![image](https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/655acec0-5e7a-464f-b704-d26bc986d536)

Changed to dropdown, used useBackend to get all drivers and shifts, and mapped the driver names to each shift using driver id.

<img width="577" alt="image" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/80604e05-b140-406e-9ca3-d7c7f7dd7c0a">

Closes #6

2024-05-17 19:02 UTC, pconrad requested changes
LGTM overall...  one thing to fix (in two places)

2024-05-17 19:02 UTC, pconrad commented on frontend/src/main/components/Ride/RideAssignDriverForm.js
> +    // Stryker enable all
```suggestion
    // Stryker restore all
```

It turns out `enable all` isn't a thing.

2024-05-17 19:02 UTC, pconrad commented on frontend/src/main/components/Ride/RideAssignDriverForm.js
>      // Stryker enable all
```suggestion
    // Stryker restore all
```

2024-05-17 20:29 UTC, Tommygithubaccount123 approved these changes, later dismissed
LGTM

2024-05-18 20:51 UTC, Ononymous commented
> LGTM overall... one thing to fix (in two places)

Fixed stryker enable

2024-05-23 01:10 UTC, pconrad approved these changes
LGTM

2024-05-23 01:10 UTC, merged