(NOT FIXED) Fix BUG: Github repo link is hardcoded #18
ucsb-cs156-s24/proj-gauchoride-s24-5pm-5 pull request #36
Opened 2024-05-23 01:31 UTC by Tommygithubaccount123

When clicking the Github hyperlink on the footer, the link routes to a hardcoded github repo. Instead this should be dynamic and be based on the repo specified in the system info. By default the link can go to proj-gauchoride in the ucsb-cs156 organization. This also requires the issue "FEATURE - expose commit infomation at /api/systemInfo" to be completed, since that issue adds the github repo to the system info.

After the issue "FEATURE - expose commit infomation at /api/systemInfo" is completed, modify Footer.js to use the systeminfo instead of a hardcoded value.

Closes #18

2024-05-25 22:39 UTC, pconrad requested changes
See hints here: 

https://ucsb-cs156-s24.slack.com/archives/C06RP83BA83/p1716676103256029

Also see code review below.

2024-05-25 22:44 UTC, pconrad requested changes
A few hints for getting this working.  

You'll also need to change BasicLayout.js to pass systemInfo into it (the same way it's passed into AppNavbar)

2024-05-25 22:44 UTC, pconrad commented on frontend/src/main/components/Nav/Footer.js
> +  }, []);
Suggest removing all of this, and instead, pass systemInfo into the component in BasicLayout.js.

2024-05-25 22:44 UTC, pconrad commented on frontend/src/main/components/Nav/Footer.js
>  export default function Footer() {
```suggestion
export default function Footer({systemInfo}) {
```

2024-05-25 22:44 UTC, pconrad commented on frontend/src/main/components/Nav/Footer.js
> +import { useEffect, useState } from "react";
```suggestion

```

2024-05-25 22:44 UTC, pconrad commented on frontend/src/main/components/Nav/Footer.js
> +            // use api/systemInfo to get the repo URL
```suggestion
```

2024-05-25 22:44 UTC, pconrad commented on frontend/src/main/components/Nav/Footer.js
> +            href={repoUrl}
```suggestion
            href={systemInfo?.sourceRepo}
```

2024-05-25 22:44 UTC, pconrad commented on frontend/src/tests/components/Nav/Footer.test.js
> +          })
You won't need to do the axiosMock if you make this a prop.

2024-05-25 22:44 UTC, pconrad commented on frontend/src/tests/components/Nav/Footer.test.js
>          render(<Footer />)
```suggestion
        const systemInfo = { sourceRepo: "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5"};
        render(<Footer systemInfo={systemInfo} />)
```

2024-05-25 22:44 UTC, pconrad commented on frontend/src/tests/components/Nav/Footer.test.js
> +        // );
```suggestion
        expect(screen.getByTestId("footer-source-code-link")).toHaveAttribute(
             "href",
             "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5"
         );
```

2024-05-25 23:47 UTC, Tommygithubaccount123 commented
The link doesn't show up now, I am not sure what is going on:
![image](https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/79723996/c3ec52a2-dbc2-4622-84d5-958a1f24d7ac)

2024-05-27 22:36 UTC, Ononymous approved these changes
LGTM

2024-05-28 01:03 UTC, pconrad approved these changes
LGTM

2024-05-28 01:03 UTC, merged

2024-06-11 05:00 UTC, maidang111 commented
LGTM