Improve usability of the DriverAvailabilities Create Page
ucsb-cs156-s24/proj-gauchoride-s24-5pm-5 pull request #37
Opened 2024-05-23 03:55 UTC by Ononymous

### As a...

driver

###I can...

Undestand what each of the form fields mean

###So that...

i can submit a correct availability without running into issues

<img width="420" alt="image" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/fee80761-fa4e-4690-9d51-a58935949372">

<img width="574" alt="image" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/4815a90d-55b4-4f65-81f2-966b31c9440a">

Create and Edit driver availability page required the input of driver id, which was not very user friendly.

The current page does not require that field for the POST request. Instead, the backend automatically adds the driver id in the post request to database.

Also, added a check such that the Get single, Delete, and Edit requests only allow availability entries of this specific user/driver.

Closes #13

2024-05-23 06:54 UTC, Tommygithubaccount123 approved these changes, later dismissed
LGTM

Damn nice, I didn't know to use `getCurrentUser().getUser().getId();` for ID

2024-05-23 21:10 UTC, Tommygithubaccount123 requested changes
IMPORTANT:

I added changes to my branch, so you need to merge my changes into your branch!!!!
https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/29

2024-05-25 02:33 UTC, Ononymous commented
> IMPORTANT:
> 
> I added changes to my branch, so you need to merge my changes into your branch!!!! #29

Merged conflicts and new changes from branch

2024-05-25 04:54 UTC, Tommygithubaccount123 submitted a review, later dismissed
LGTM

2024-05-26 00:39 UTC, Ononymous commented
@pconrad Added deployed link, with 2 test availabilities inputted

2024-05-28 10:40 UTC, Ononymous commented
@pconrad 
Sorry about the extra step. The environment variable has been fixed. It seems that I have repeated the word "ADMIN_EMAILS=" twice, resulting in professor's email to be invalid.

<img width="857" alt="image" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/598245b1-37bb-40ca-b76e-c5dfb32d24d9">

2024-06-05 01:20 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +            throw new EntityNotFoundException(DriverAvailability.class, id);
This is not the correct exception to throw.  This should only be used when you did a search for a DriverAvailability with a certain id and it was not found.  Throwing this exception will cause future devs to curse your name.

The exception you want is one that will turn into a 403 unauthorized, but if you can't figure out how to do that, then just throw a generic exception with a reasonable error message.

2024-06-05 01:20 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +                .orElseThrow(() -> new EntityNotFoundException(DriverAvailability.class, id));
This is the correct use of this exception,

2024-06-05 01:20 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
> +        if (availability.getDriverId() != getCurrentUser().getUser().getId()) {
Member
@[pconrad](https://github.com/pconrad) pconrad [Jun 4, 2024](https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/pull/37/files#r1626804244)

This is not the correct exception to throw. This should only be used when you did a search for a DriverAvailability with a certain id and it was not found. Throwing this exception will cause future devs to curse your name.

The exception you want is one that will turn into a 403 unauthorized, but if you can't figure out how to do that, then just throw a generic exception with a reasonable error message.
@pconrad

2024-06-05 01:21 UTC, pconrad requested changes
This code is throwing a misleading exception.

Please fix; otherwise this is not mergable.  You have only until I finish with other team's PRs, or the end of section tomorrow night, which ever is sooner.

2024-06-05 03:42 UTC, Ononymous commented
> This code is throwing a misleading exception.
> 
> Please fix; otherwise this is not mergable. You have only until I finish with other team's PRs, or the end of section tomorrow night, which ever is sooner.

@pconrad Hi Professor, I just pushed the new commit that modified the exception behavior for 403 forbidden in Driver Availability.

I temporarily added the fixes from PR #45 , and it is working in swaggers when I try edit/delete/get a driver availability that doesn't belong to the user.

<img width="1450" alt="image" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/assets/36137654/e334dbea-de84-494c-b622-9e3aab9d70b6">

2024-06-06 00:23 UTC, rileychou submitted a review, later dismissed
LGTM, nice fix on the Forbidden error messages.

2024-06-06 15:43 UTC, pconrad requested changes
I don't see any problems with the code, per se, but when I go to test this, I'm just confused.  There are two shift menus on the navbar, and I'm not sure which I should be testing.  One of them has backend errors showing, up, and the other doesn't seem to match the PR.

Can you make a more clear test plan?  And consider cleaning up the UI issues that make it confusing to use and test?

2024-06-07 01:05 UTC, pconrad approved these changes, later dismissed
LGTM

2024-06-07 01:06 UTC, merged